In [ ]:
# NumPy allows homogenous data to be stored
import numpy
a=numpy.array((1,22,6,54,12))
print(type(a))
print(a)

<class 'numpy.ndarray'>
[ 1 22  6 54 12]


In [ ]:
import numpy as np
b=np.zeros(3) # Creates array of size 3 with 0 as all elements
c=np.ones(4)
print(b)
print(c)

[0. 0. 0.]
[1. 1. 1. 1.]


In [ ]:
import numpy as np
d=np.sort(a)
print(d)

[ 1  6 12 22 54]


In [1]:
# Single Dimensional Array
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
# Multi Dimensional Array
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#a
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
import numpy as np
a=np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
import numpy as np
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
import numpy as np
a=np.full((2,5),46) # full(number of rows,number of columns,value)
a

array([[46, 46, 46, 46, 46],
       [46, 46, 46, 46, 46]])

In [15]:
import numpy as np
a=np.arange(10,30,1) # arange(initial value,final value,increment value)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [19]:
import numpy as np
a=np.random.randint(1,999,6) # randint(initial value,final value,number of values)
a

array([ 15, 385, 824, 410,  78, 367])

Shaping of NumPy arrays

In [32]:
# Shaping of NumPy Array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print()
#a.shape
a.shape=(3,2)
#a.shape
print(a)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


Joining NumPy Arrays

In [38]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
c
#print(c)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.column_stack((a,b))
c

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])


NumPy Intersection and Difference

In [42]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
np.intersect1d(a,b)

array([3, 4])

In [46]:
np.setdiff1d(a,b)
np.setdiff1d(b,a)

array([5, 6])

NumPy Mathematics

In [48]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
np.sum([a,b])

28

In [51]:
np.sum([a,b],axis=0) #Addition of individual columns

array([ 4,  6,  8, 10])

In [52]:
np.sum([a,b],axis=1) #Addition of individual rows

array([10, 18])

In [54]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
d=np.array([5,6,7,8])
a=a+1
b=b*2
c=c-1
d=d/2
print("a+1=",a)
print("b*2=",b)
print("c-1=",c)
print("d/2=",d)

a+1= [2 3 4 5]
b*2= [10 12 14 16]
c-1= [0 1 2 3]
d/2= [2.5 3.  3.5 4. ]


NumPy Mean, Median and Standard Deviation

In [60]:
import numpy as np
a=np.array([10,48,23,9,45,61 ])
print("Standard Deviation ",np.std(a))
print("Mean ",np.mean(a))
print("Median ",np.median(a))

Standard Deviation  19.821424996424675
Mean  32.666666666666664
Median  34.0


NumPy Save

In [61]:
np.save("my_numpy",a)